### ISSUE TITLE
standalone-custom-memory-config.yaml is formatted incorrectly so resource requests are ignored

### ISSUE THREAD

**Issue by davidlrosenblum** [neo4j-contrib/neo4j-helm#114]
In standalone-custom-memory-config.yaml the resources are at the wrong indent. Should look like:

```
core:
    standalone: true 
    resources:
        limits:
            memory: 4G
        requests:
            memory: 4G
```
  
not like:

```
core:
    standalone: true

resources:
    limits:
        memory: 4G
    requests:
        memory: 4G
```
