### ISSUE TITLE
Define container securityContext

### ISSUE THREAD

**Issue by jpugliesi** [neo4j-contrib/neo4j-helm#135]
Currently, `securityContext` is undefined for all containers in the neo4j statefulset.

What uid should be used in the neo4j container? [It looks like a neo4j user exists in the container](https://github.com/neo4j/docker-neo4j-publish/blob/master/4.1.3/community/Dockerfile#L11), but is not set as the container user (via docker's `USER` statement)

Example `securityContext`:
```
securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 7474
              runAsGroup: 7474
              fsGroup: 7474
```

**Comment by moxious** [comment]
This is an issue I'm less familiar with. Suppose we defined the default security context to be this, and made it configurable via values.   With something like this as the defaults, what undesirable things would this prevent?   What desirable things would this enable?

**Comment by moxious** [comment]
Reference this PR:  https://github.com/neo4j-contrib/neo4j-helm/pull/143

This PR for the moment will be left open for comment & discussion.  I did more research here and want to point out some issues.

While it's true that the Neo4j container runs as user 7474 and as non-root, it's also true that the Dockerfile doesn't have a `USER` statement, and that it *starts as root* and then lowers its permissions when running the main Neo4j entrypoint.  The reason for this is historical support cases dealing with filesystem permissions.   The container needs to be able to have the Neo4j user & group own the files & directories relevant for logs, data files, etc.   When volumes are mounted that don't already have the right permissions, root access is needed to change this so the container works.

When security groups are put in place which don't permit using the root user, large exceptions can result as the docker container fails to assign privileges needed.

In the PR -- what I'm doing right now is assigning a default **totally empty** securityContext of `{}`.  This means that the helm chart "just works", and securityContext is now configurable for users who know what they're doing...but really nothing has changed.

Users who know about the filesystem permissions & have taken steps to see things happen properly can set the securityContext that's right for them, while we retain a functional default for users who haven't investigated all of those issues yet.

Comments welcome.  This will remain open for a bit.

**Comment by EarthlingDavey** [comment]
I couldn't find many resources for how to set persistant volume permissions.
The below values for this helm chart work for me.

Apologies if this is the wrong place to share, but this info seems so hard to find, and this pace is linked from the helm docs.

```
  values:
    # ...
    securityContext:
      { runAsNonRoot: true, runAsUser: 7474, runAsGroup: 7474, fsGroup: 7474 }
    core:
      persistentVolume:
        size: <changeme>
        storageClassName: <changeme>
        annotations:
          pv.beta.kubernetes.io/gid: "7474"
          volume.beta.kubernetes.io/mount-options: "uid=7474,gid=7474"
    # ...
```
