### ISSUE TITLE
Helm Repo Index contains a chart with no version

### ISSUE THREAD

**Issue by elioengcomp** [neo4j-contrib/neo4j-helm#161]
**Describe the bug**
Hi there! I'm a maintainer of [ChartCenter](https://chartcenter.io/) and we are seeing some issues related to discovering new chart releases from https://neo4j-contrib.github.io/neo4j-helm. It seems there is one chart entry that contains no version information in the index file.

**To Reproduce**
1. Fetch https://neo4j-contrib.github.io/neo4j-helm/index.yaml
2. The first neo4j entry has no version:

```
neo4j:
    - created: 2021-01-20T00:09:00.499814565-06:00
      description: 4.2.2-1
      digest: 4484d915b96f09f6d558796060f2e271479f4d98e2fb21bb80477f208cfe1226
      home: https://github.com/neo4j-contrib/neo4j-helm
      name: neo4j
      sources:
      - https://github.com/neo4j-contrib/neo4j-helm
      urls:
      - https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.2.2-1/neo4j-4.2.2-1.tgz
```

**Expected behavior**
All chart entries in the index file should contain a version:

```
    - created: 2020-11-30T00:09:00.499814565-06:00
      description: 4.2.0-1
      digest: 5714ecc77821fcbf00398da7fa9f2eb62913ece97dc45124bf35f977380ed435
      home: https://github.com/neo4j-contrib/neo4j-helm
      name: neo4j
      sources:
      - https://github.com/neo4j-contrib/neo4j-helm
      urls:
      - https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.2.0-1/neo4j-4.2.0-1.tgz
      version: 4.2.0-1
```

**Error Logs**
DNA

**Additional context**
DNA
