### ISSUE TITLE
Error: No jar URL found for version '4.2.2' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

### ISSUE THREAD

**Issue by survivant** [neo4j-contrib/neo4j-helm#168]
I recreate my cluster yesterday (reinstall new OS on each nodes).  I'm trying to redeploy neo4j in the cluster, but I got this error

````
apiVersion: v1
appVersion: 4.2.2
description: Neo4j is the world's leading graph database
home: https://www.neo4j.com
icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
keywords:
- graph
- database
- cypher
maintainers:
- email: david.allen@neo4j.com
  name: moxious
- email: bledi.feshti@neo4j.com
  name: bfeshti
- email: mark.needham@neo4j.com
  name: mneedham
name: neo4j
sources:
- https://github.com/neo4j/neo4j
- https://github.com/neo4j/docker-neo4j
- https://github.com/neo4j-contrib/neo4j-helm
version: 4.2.2-1
````

````
root@test-pcl109:~# kubectl logs twin-neo4j-core-0 --follow
Configuration override prefix = twin_neo4j_core_0
Starting Neo4j CORE 0 on twin-neo4j-core-0.twin-neo4j.default.svc.cluster.local
Warning: Some files inside "/data" are not writable from inside container. Changing folder owner to neo4j.
Changed password for user 'neo4j'.
VM settings:
    Min. Heap Size: 4.00G
    Max. Heap Size: 4.00G
    Using VM: OpenJDK 64-Bit Server VM

Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Error: No jar URL found for version '4.2.2' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

root@test-pcl109:~#

````

in the init process, the script is trying to retrieve apoc with version 4.2.2   but in  'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'  the versions have 4 digits :  4.2.2.0

like
````
{
        "neo4j": "4.2.1",
        "neo4jVersion": "4.2.1",
        "apoc": "4.2.0.0",
        "version": "4.2.0.0",
        "url": "http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.2.0.0",
        "homepageUrl": "http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.2.0.0",
        "jar": "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.0/apoc-4.2.0.0-all.jar",
        "downloadUrl": "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.0/apoc-4.2.0.0-all.jar",
        "sha1": "e58cb627d96260c8a062692320c2f09ba66b0641",
        "sha256": "ab8dff9cbb5e4185f4242c2a111e50e0d368c28234e9e5824915f0f9842c1887",
        "md5": "c819a1a7d5b822ef2676d966e4d29d25",
        "config": {
            "+:dbms.security.procedures.unrestricted": [
                "apoc.*"
            ]
        }
    },
````
