### ISSUE TITLE
Cannot Parse String in Pod Annotations

### ISSUE THREAD

**Issue by mohammadsrahman** [neo4j-contrib/neo4j-helm#192]
When trying to add annotations in the form of strings the STS is not complying to the order of Maps.

Example I want to add the following annotation:

```
podAnnotations:
        proxy.istio.io/config: |
            tracing:
              sampling: 0
```

This results in the following error:

`* invalid value 'map[proxy.istio.io/config:tracing: sampling: 0 ]' for annotation 'proxy.istio.io/config': failed to convert to apply proxy config: yaml: mapping values are not allowed in this context`

The template for the STS contains the following:

```
      {{- if .Values.podAnnotations }}
      annotations:
        {{-  range $key, $value := .Values.podAnnotations }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
```
A fix for this would be changing to:

```
{{- with .Values..podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
{{- end }}
```
