### ISSUE TITLE
Unable to set apoc.trigger.enabled in neo4j.conf

### ISSUE THREAD

**Issue by ashwin-ginoria** [neo4j-contrib/neo4j-helm#211]
**Describe the bug**
values.yaml unable to set apoc.trigger.enabled in neo4j.conf
neo4j version 4.3.2
helm version v3.6.3
chart version 4.3.2-1

**To Reproduce**
1.  Run with values
```
neo4j:
  password: "my-password"
  resources:
    cpu: "2"

# Neo4j configuration (yaml format)
config:
  apoc.trigger.enabled: "true"
  dbms.default_database: "neo4j"
  dbms.config.strict_validation: "true"
  dbms.connector.https.enabled: "true"
```
2. run `helm install mygraph  https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.3.2-1/neo4j-4.3.2-1.tgz --set core.standalone=true --set acceptLicenseAgreement=yes --set neo4jPassword=mySecretPassword -f values.yml` 
3. Go to neo4j browser and run `CALL apoc.trigger.list()`

**Expected behavior**
Should return an empty list in neo4j browser.
