### ISSUE TITLE
Prometheus Endpoint fails

### ISSUE THREAD

**Issue by jamesdhope** [neo4j-contrib/neo4j-helm#213]
**Describe the bug**
I am deploying neo as a single core (or casual cluster) via the helm chart 4.2.8-1 as I need plugins that only support neo4.2. 

When i expose the prometheus endpoint through the helm chart the log output looks incorrectly.

```

  prometheus:
    ## Publish metrics for polling as Prometheus endpoint
    enabled: true
    endpoint: "0.0.0.0:2004"

```

Neo4j log output:

**publishing Prometheus metrics at http:///0:0:0:0:0:0:0:0:2004/metrics**

**Additional context**

* I have attempted to set the metrics endpoint in neo4j.conf via a ConfigMap. This also fails.
