### ISSUE TITLE
Can't change log format

### ISSUE THREAD

**Issue by wufengzlw** [neo4j-contrib/neo4j-helm#233]
Hi,

I met this log format issue, can't change log format because can't pass config in values.yaml into neo4j.conf

**Describe the bug**
Deployed Neo4j 4.3.6 with helm only with this dbms related config in values.yaml:
```
dbms:
    memory:
        pagecache:
            size: 512m
```
it's working, I can get this config from neo4j.conf:
```
$ k exec neo4j-neo4j-replica-0 -n neo4j -- cat conf/neo4j.conf | grep dbms.memory.page
#dbms.memory.pagecache.size=10g
dbms.memory.pagecache.size=512m
```

When I tried to modify log format to json by adding this to values.yaml in two ways:
```
  set {
    name  = "dbms.logs.default_format"
    value = "json"
  }
```
or 
```
dbms:
    memory:
        pagecache:
            size: 512m
    logs:
        default_format: json
```

I can't find this config in neo4j.conf (even after restart the sts):
`k rollout restart sts neo4j-neo4j-replica -n neo4j`

**To Reproduce**
1. Install with these values
2. Go to ....

**Expected behavior**
the log related config can  be passed to neo4j.conf

**Error Logs**
If applicable, add the contents of your debug.log file
no error log

**Additional context**
