### ISSUE TITLE
Look into I/O Throttling

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-helm#35]
From Jake:

```
version: "2"
​
x-core-common:
  &core-common
  NEO4J_AUTH: neo4j/secret
  NEO4J_dbms_mode: CORE
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_causal__clustering_minimum__core__cluster__size__at__formation: 3
  NEO4J_causal__clustering_minimum__core__cluster__size__at__runtime: 3
  NEO4J_causal__clustering_initial__discovery__members: core1:5000,core2:5000,core3:5000
​
services:
  core1:
    container_name: core1
    image: neo4j:4.0-enterprise
    cap_add:
      - NET_ADMIN
    ports:
      - 7474:7474
    blkio_config:
      device_read_bps:
        - path: /dev/mapper/mint--vg-root
          rate: '30mb'
      device_read_iops:
        - path: /dev/mapper/mint--vg-root
          rate: '1920'
      device_write_bps:
        - path: /dev/mapper/mint--vg-root
          rate: '30mb'
      device_write_iops:
        - path: /dev/mapper/mint--vg-root
          rate: '1920'
    environment:
      <<: *core-common
      NEO4J_dbms_connector_bolt_advertised__address: core1:7687
      NEO4J_dbms_connector_http_listen__address: :7474
      NEO4J_causal__clustering_discovery__advertised__address: core1:5000
​
  core2:
    container_name: core2
    image: neo4j:4.0-enterprise
    cap_add:
      - NET_ADMIN
    ports:
      - 7475:7475
    blkio_config:
      device_read_bps:
        - path: /dev/mapper/mint--vg-root
          rate: '30mb'
      device_read_iops:
        - path: /dev/mapper/mint--vg-root
          rate: '1920'
      device_write_bps:
        - path: /dev/mapper/mint--vg-root
          rate: '30mb'
      device_write_iops:
        - path: /dev/mapper/mint--vg-root
          rate: '1920'
    environment:
      <<: *core-common
      NEO4J_dbms_connector_bolt_advertised__address: core2:7687
      NEO4J_dbms_connector_http_listen__address: :7475
      NEO4J_causal__clustering_discovery__advertised__address: core2:5000
​
  core3:
    container_name: core3
    image: neo4j:4.0-enterprise
    cap_add:
      - NET_ADMIN
    ports:
      - 7476:7476
    blkio_config:
      device_read_bps:
        - path: /dev/mapper/mint--vg-root
          rate: '30mb'
      device_read_iops:
        - path: /dev/mapper/mint--vg-root
          rate: '1920'
      device_write_bps:
        - path: /dev/mapper/mint--vg-root
          rate: '30mb'
      device_write_iops:
        - path: /dev/mapper/mint--vg-root
          rate: '1920'
    environment:
      <<: *core-common
      NEO4J_dbms_connector_bolt_advertised__address: core3:7687
      NEO4J_dbms_connector_http_listen__address: :7476
      NEO4J_causal__clustering_discovery__advertised__address: core3:5000
```
