### ISSUE TITLE
DMBS memory heap and pagecache configurations are ignored

### ISSUE THREAD

**Issue by diegoep** [neo4j-contrib/neo4j-helm#40]
I'm trying to deploy neo4j via Helm using the latest chart version (4.1.0) but it seems the `dbms`configuration is being just ignored.
Here is the configuration in my values.yaml:
```
dbms:
  memory:
    use_memrec: false
    heap:
      initial_size: "8G"
      max_size: "8G"
    pagecache:
      size: "8G"
```
I've checked the file conf/neo4j.conf and also did a cypher query to get the current configuration and in both there was no changes, it remains the initial neo4j configuration. Here was the Cypher query that I ran:
```
CALL dbms.listConfig()
YIELD name, value
WHERE name STARTS WITH 'dbms'
RETURN name, value
ORDER BY name;
```

I've also looked at the templates and I didn't find anything that reads this property and applies it into the config.
