### ISSUE TITLE
Seems like the implementation of additionalVolumeMounts and additionalVolumes might be broken

### ISSUE THREAD

**Issue by JnMik** [neo4j-contrib/neo4j-helm#66]
Hello guys ! 

I have issues when using these 2 properties in values.yml, like this :  
```

  ## specify additional volumes to mount in the core container, this can be used
  ## to specify additional storage of material or to inject files from ConfigMaps
  ## into the running container
  additionalVolumes:
  - name: restore-service-key
    secret:
      secretName: neo4j-cronjob-backup
      defaultMode: 0555
  - name: restore-script
    configMap:
      name: "neo4j-cronjob-script"
      defaultMode: 0777
  - name: "neo4j-tls"
    secret:
      secretName: "neo4j-tls"

  ## specify where the additional volumes are mounted in the core container
  additionalVolumeMounts:
  - name: "neo4j-tls"
    mountPath: "/certs/bolt/public.crt"
    subPath: "tls.crt"
    readOnly: true
  - name: "neo4j-tls"
    mountPath: "/certs/bolt/private.key"
    subPath: "tls.key"
    readOnly: true
```

I receive these warnings: 
```
coalesce.go:196: warning: cannot overwrite table with non table for additionalVolumeMounts (map[])
coalesce.go:196: warning: cannot overwrite table with non table for additionalVolumes (map[])
```
If I replace the curly brackets by square brackets in the values.yml, everything is working as expected

```
sed -i 's/additionalVolumes: {}/additionalVolumes: []/g' $MYDIR/neo4j-helm/values.yaml
sed -i 's/additionalVolumeMounts: {}/additionalVolumeMounts: []/g' $MYDIR/neo4j-helm/values.yaml

Results: 

  ## specify additional volumes to mount in the core container, this can be used
  ## to specify additional storage of material or to inject files from ConfigMaps
  ## into the running container
  additionalVolumes: []

  ## specify where the additional volumes are mounted in the core container
  additionalVolumeMounts: []
```

We started a discussion about this here in the merge request (unfortunately it was already closed) : https://github.com/neo4j-contrib/neo4j-helm/pull/54

So this issue would complement (or fix) this one https://github.com/neo4j-contrib/neo4j-helm/issues/46

Thanks @moxious  for hearing me out :1st_place_medal:
