### ISSUE TITLE
improve service that is used to expose the cluster for consumption by clients

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-helm#83]
Add `com.neo4j.<something>` labels so we can get hold of it easily using the Kubernetes API & label selectors - this is the biggie.

Does it need `publishNotReadyAddresses: true` any more? might be better to remove it if not needed.

**Comment by moxious** [comment]
The services already have appropriate labels that get generated like this:

```
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/name: {{ template "neo4j.name" . }}
    app.kubernetes.io/component: core
```

This lets you know for sure that:
- It's neo4j
- It's helm installed
- Which chart version installed it
- Helm manages it

What else would we need to express not captured by that?    The actual labels chosen are helm conventions, which explains why none of it is `com.neo4j.whatever`.

RE: do we need publishNotReadyAddresses?   My understanding is yes we definitely need them.   To form a cluster, it has to be able to contact the service.  If the service doesn't form until the container is ready, then you have an unsatisfiable catch-22 because causal cluster can't come available until it discovers the other cluster members.   If this is not the case, then please expand

**Comment by eastlondoner** [comment]
We have "discovery" services I am going to call them that because that's the name they're given in helm charts, although they do all internal services and we have what I am going to call "bolt and http" Services.

The labels I would like are something that allows me to distinguish between the two when writing a label selector. The Labels you point out logically apply to both.

The "bolt and http" services are the ones that I don't think need to be enabled when pods aren't ready. I am fully aware of the need for that on the "discovery" services.

**Comment by moxious** [comment]
OK I think I better see what you mean.   What would better help discriminate?

The labels I pasted above are those on the user-facing bolt/https service.   The ones on the internal discovery service are as follows:

```
metadata:
  name: discovery-{{ template "neo4j.fullname" $dot }}-{{ . }}
  labels:
    neo4j.com/coreindex: "{{ $index }}"
    neo4j.com/cluster: {{ template "neo4j.fullname" $dot }}
    neo4j.com/role: CORE
    app.kubernetes.io/managed-by: {{ $dot.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
    helm.sh/chart: "{{ $dot.Chart.Name }}-{{ $dot.Chart.Version }}"
    app.kubernetes.io/name: {{ template "neo4j.name" $dot }}
    app.kubernetes.io/component: core
```

As the discovery service has a neo4j.com/coreindex (which is already targeted by the label selector for discovery) - there's already a way to discriminate between the internal & external services.  But perhaps I don't get the use case right.

Which label on which service gets you what you're requesting?
