### ISSUE TITLE
Additional Volume values - map or list

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-helm#97]
In values.yaml we have

```
core:
  additionalVolumes: []
  additionalVolumeMounts: []

readReplica:
  additionalVolumes: {}
  additionalVolumeMounts: {}
```

can we be consistent about whether we use a list or a dict ? 
I suggest changing the readReplicas to list
